/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.test.userinterface;


import com.test.daoimpl.CityDAOImpl;
import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.test.dao.UserDAO;
import com.test.daoimpl.UserDAOImpl;
import com.test.models.UserModel;
import java.util.regex.Pattern;
import javax.swing.JLabel;
import javax.swing.JTextField;
import com.test.dao.CityDAO;

/**
 *
 * @author Ahsan
 */
public class UserFrame extends javax.swing.JFrame {

    /**
     * Creates new form RegisterationForm
     */
   UserModel user;
   JTextField emailLogin, passwordLogin;
   
    public UserFrame(UserModel tempUser, JTextField emailLog, JTextField passwordLog) {
        initComponents();
        //noEmailLbl.setText("");
        //noEmailLbl.setVisible(false);
        emailLogin = emailLog;
        passwordLogin = passwordLog;
        
        noEmailLbl.setForeground(Color.WHITE);
        
        this.user = tempUser;
        
        CityDAO countryDAO = new CityDAOImpl();
        
        buttonGroup1.add(maleRadio);
        buttonGroup1.add(femaleRadio);
        
        //Set User Name
        nameField.setText(user.getName());
        emailField.setText(user.getEmail());
        emailField.setEditable(false);
        passwordField.setText(user.getPassword());
        
        System.out.println(user.getGender());
        
        System.out.println(user.getGender().equalsIgnoreCase("male"));
        if(user.getGender().equalsIgnoreCase("male")){    
            maleRadio.setSelected(true);
        }
        else{    
            femaleRadio.setSelected(true);
        }
        
        countryCombo.addItem("          -------SELECT------");
        
        for(String c : countryDAO.getAllCountryNames()){
            countryCombo.addItem(c);
        }
        System.out.println(new CityDAOImpl().getSpecificCountryName(user.getCityId()));
        countryCombo.setSelectedItem(new CityDAOImpl().getSpecificCountryName(user.getCityId()));
        
        this.getContentPane().setBackground( new Color(153,153,255) );
    }
    
    boolean isValidData(){
    
        if(nameField.getText().trim().isEmpty()){
            
            JOptionPane.showMessageDialog(this, "No Name!");
        }
        //else if(emailField.getText().trim().isEmpty()){
        else if(!LoginJFrame.isValidEmail(emailField.getText().trim())){  
            
            JOptionPane.showMessageDialog(this, "No Email or Invalid Email!");
        }
        //else if(passwordField.getText().trim().isEmpty()){
        else if(!LoginJFrame.isValidPassword(passwordField.getText().trim().toCharArray())){
        
            JOptionPane.showMessageDialog(this, "No Password or Invalid Password!");
        }
        else if(!(maleRadio.isSelected() || femaleRadio.isSelected())){
            
            JOptionPane.showMessageDialog(this, "No Gender!");
        }
        else if(countryCombo.getSelectedItem().toString().equals(countryCombo.getItemAt(0))){
            
            JOptionPane.showMessageDialog(this, "No Department!");
        }     
        else if(countryCombo.getSelectedItem().toString().equals(countryCombo.getItemAt(0))){
            
            JOptionPane.showMessageDialog(this, "No City!");
        }
        else{
            return true;
        }
        return false;
    }

    UserModel getAllUserData(){
        
        String name = nameField.getText().trim();
        String email = emailField.getText().trim();
        String password = passwordField.getText().trim();
        String gender = "";
        
        if(maleRadio.isSelected()){
            gender = (maleRadio.getText());
        }
        else{
            gender = (femaleRadio.getText());
        }
        
        Integer cityId = (new CityDAOImpl().getSpecificCountryId(countryCombo.getSelectedItem().toString().trim()));
       
        UserModel s = new UserModel(name, email, password, gender, cityId);
        System.out.println(s);
        return s;
    }
   
    void resetValues() {

        nameField.setText("");
        emailField.setText("");
        passwordField.setText("");
        maleRadio.setSelected(false);
        femaleRadio.setSelected(false);
        countryCombo.setSelectedIndex(0);
        countryCombo.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        headLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        emailLbl = new javax.swing.JLabel();
        CityCombo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        maleRadio = new javax.swing.JRadioButton();
        femaleRadio = new javax.swing.JRadioButton();
        countryCombo = new javax.swing.JComboBox<>();
        updateBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        noEmailLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 255));
        setResizable(false);

        headLbl.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        headLbl.setText("WELCOME");

        nameLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nameLbl.setText("Name");

        emailLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        emailLbl.setText("Email");

        CityCombo.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        CityCombo.setText("City");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setText("Gender");

        passwordLbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        passwordLbl.setText("Password");

        nameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFieldActionPerformed(evt);
            }
        });
        nameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nameFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nameFieldKeyTyped(evt);
            }
        });

        emailField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailFieldMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailFieldMouseExited(evt);
            }
        });
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailFieldKeyTyped(evt);
            }
        });

        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordFieldKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });

        maleRadio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        maleRadio.setText("Male");

        femaleRadio.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        femaleRadio.setText(" Female");

        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        deleteBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        noEmailLbl.setBackground(new java.awt.Color(255, 0, 0));
        noEmailLbl.setForeground(new java.awt.Color(255, 0, 0));
        noEmailLbl.setText("Can't Change !");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(68, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CityCombo)
                            .addComponent(nameLbl)
                            .addComponent(emailLbl)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordLbl)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(maleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(femaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(noEmailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(headLbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(98, 98, 98)
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73)
                                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(headLbl)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLbl)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLbl)
                    .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noEmailLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(femaleRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maleRadio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CityCombo))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        
        UserDAO dao;
                
        int result = JOptionPane.showConfirmDialog(this, "Are you sure?");
        
        if(JOptionPane.YES_OPTION == result){
            
            if(isValidData()){
            
                dao = new UserDAOImpl();
                int id = user.getId();

                user = getAllUserData();
                user.setId(id);
                if( dao.update(user) >= 1){

                    System.out.println("Updated Successfully!");
                }
                else {
                    System.out.println("NOT update Successfully!");
                }
            }
            
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void nameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyReleased
        // TODO add your handling code here:
       
    }//GEN-LAST:event_nameFieldKeyReleased

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void passwordFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyReleased
       
        
    }//GEN-LAST:event_passwordFieldKeyReleased

    private void nameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFieldActionPerformed
       
        emailField.requestFocusInWindow();
       
    }//GEN-LAST:event_nameFieldActionPerformed

    private void nameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameFieldKeyTyped
        
        char c = evt.getKeyChar();
        System.out.println(c + "h");
        System.out.println(Character.isWhitespace(c));
        System.out.println(Character.isSpaceChar(c));
        System.out.println(Character.toString(c).equals(" "));
        if(!(Character.isLetter(c) || Character.isISOControl(c)|| Character.isWhitespace(c) || Character.isSpaceChar(c) || Character.toString(c).equals(" "))){
        
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Only Numbers and Letters!");
        }
    }//GEN-LAST:event_nameFieldKeyTyped

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
       
        /*char c = evt.getKeyChar();
        
        if(!(Character.isLetterOrDigit(c) || Character.isISOControl(c))){
        
            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Only Numbers and Letters!");
        }*/
        
        char c = evt.getKeyChar();
        String x = Character.toString(c);
        
        if(!(Character.isLetterOrDigit(c) || Character.isISOControl(c) || Pattern.matches("[!@#$]", x))){
            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Letters & Numbers only!");
        }
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void emailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyTyped
        // TODO add your handling code here:
        /*char c = evt.getKeyChar();

        if(!(Character.isLetter(c) || Character.isDigit(c)|| Character.isISOControl(c) || Character.isSpaceChar(c))){

            evt.consume();
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Not Allowed!");
        }*/
        
        char c = evt.getKeyChar();
        
        if(!(Character.isLetterOrDigit(c) || Character.isISOControl(c) || Character.toString(c).equals(".") || Character.toString(c).equals("@"))){
            
            evt.consume();
            JOptionPane.showMessageDialog(this, "Letters, Numbers, @ and . only!");
        }
    }//GEN-LAST:event_emailFieldKeyTyped

    private void emailFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldKeyReleased

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_emailFieldActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        UserDAO dao;
        
         int result = JOptionPane.showConfirmDialog(this, "Are you sure?");
        
        if(JOptionPane.YES_OPTION == result){
            
            if(isValidData()){
            
            dao = new UserDAOImpl();
            
                if( dao.delete(user.getId()) >= 1){

                    System.out.println("Deleted Successfully!");
                    passwordLogin.setText("");
                    emailLogin.setText("");
                    dispose();

                }
                else {
                    System.out.println("NOT Deleted Successfully!");
                }
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void emailFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFieldMouseClicked
        
        //noEmailLbl.setText("Can't Change !");
        noEmailLbl.setForeground(Color.RED);
        //noEmailLbl.setVisible(true);
    }//GEN-LAST:event_emailFieldMouseClicked

    private void emailFieldMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailFieldMouseExited
        
        //noEmailLbl.setText("Can't Change !");
        noEmailLbl.setForeground(Color.WHITE);
        //noEmailLbl.setVisible(false);
    }//GEN-LAST:event_emailFieldMouseExited

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CityCombo;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> countryCombo;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JRadioButton femaleRadio;
    private javax.swing.JLabel headLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel noEmailLbl;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
